-- MySQL Script generated by MySQL Workbench
-- Sat Sep 30 16:37:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema finanzas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema finanzas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finanzas` DEFAULT CHARACTER SET latin1 ;
USE `finanzas` ;

-- -----------------------------------------------------
-- Table `finanzas`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finanzas`.`bancos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`bancos` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`bancos` (
  `idbancos` INT(11) NOT NULL AUTO_INCREMENT,
  `banco_nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT(4) NULL DEFAULT '1',
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idbancos`),
  CONSTRAINT `fk_bancos_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COMMENT = '					';

CREATE UNIQUE INDEX `idBANCOS_UNIQUE` ON `finanzas`.`bancos` (`idbancos` ASC);

CREATE UNIQUE INDEX `banco_nombre_UNIQUE` ON `finanzas`.`bancos` (`banco_nombre` ASC);

CREATE INDEX `fk_bancos_1_idx` ON `finanzas`.`bancos` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`cuentas_bancaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`cuentas_bancaria` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`cuentas_bancaria` (
  `idcuentas_bancaria` INT(11) NOT NULL AUTO_INCREMENT,
  `num_cuenta` VARCHAR(45) NOT NULL,
  `banco_id` INT(11) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idcuentas_bancaria`),
  CONSTRAINT `banco_id`
    FOREIGN KEY (`banco_id`)
    REFERENCES `finanzas`.`bancos` (`idbancos`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_banc_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_cuentas_bancaria_UNIQUE` ON `finanzas`.`cuentas_bancaria` (`idcuentas_bancaria` ASC);

CREATE UNIQUE INDEX `num_cuenta_UNIQUE` ON `finanzas`.`cuentas_bancaria` (`num_cuenta` ASC);

CREATE INDEX `banco_id_idx` ON `finanzas`.`cuentas_bancaria` (`banco_id` ASC);

CREATE INDEX `fk_cuenta_banc_usuario_id_idx` ON `finanzas`.`cuentas_bancaria` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`chequera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`chequera` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`chequera` (
  `idchequera` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_chequera` INT(11) NOT NULL,
  `cantidad_cheques` INT(11) NOT NULL,
  `desde` INT(11) NOT NULL,
  `hasta` INT(11) NOT NULL,
  `cuenta_bancaria_id` INT(11) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idchequera`),
  CONSTRAINT `cuenta_bancaria_id`
    FOREIGN KEY (`cuenta_bancaria_id`)
    REFERENCES `finanzas`.`cuentas_bancaria` (`idcuentas_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chequera_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `cuenta_bancaria_id_idx` ON `finanzas`.`chequera` (`cuenta_bancaria_id` ASC);

CREATE INDEX `fk_chequera_1_idx` ON `finanzas`.`chequera` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`condicion_cheque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`condicion_cheque` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`condicion_cheque` (
  `idcondicion_cheque` INT(11) NOT NULL AUTO_INCREMENT,
  `condicion_cheque` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcondicion_cheque`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `finanzas`.`movimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`movimientos` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`movimientos` (
  `idmovimientos_bancarios` INT(11) NOT NULL AUTO_INCREMENT,
  `movimientos_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmovimientos_bancarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idmovimientos_bancarios_UNIQUE` ON `finanzas`.`movimientos` (`idmovimientos_bancarios` ASC);

CREATE UNIQUE INDEX `movimientos_nombre_UNIQUE` ON `finanzas`.`movimientos` (`movimientos_nombre` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`cheque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`cheque` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`cheque` (
  `idcheque` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_cheque` INT(11) NOT NULL,
  `importe_cheque` DECIMAL(10,0) NOT NULL,
  `fecha_emision` DATE NOT NULL,
  `fecha_cobro` DATE NOT NULL,
  `destinatario` VARCHAR(45) NOT NULL,
  `estado_cheque` VARCHAR(45) NULL DEFAULT NULL,
  `movimiento_bancario_id` INT NOT NULL,
  `chequera_id` INT NULL DEFAULT NULL,
  `condicion_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idcheque`),
  CONSTRAINT `chequera_id`
    FOREIGN KEY (`chequera_id`)
    REFERENCES `finanzas`.`chequera` (`idchequera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `condicion_id`
    FOREIGN KEY (`condicion_id`)
    REFERENCES `finanzas`.`condicion_cheque` (`idcondicion_cheque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `moviento_bancario_id`
    FOREIGN KEY (`movimiento_bancario_id`)
    REFERENCES `finanzas`.`movimientos` (`idmovimientos_bancarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cheque_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idcheque_UNIQUE` ON `finanzas`.`cheque` (`idcheque` ASC);

CREATE UNIQUE INDEX `numero_cheque_UNIQUE` ON `finanzas`.`cheque` (`numero_cheque` ASC);

CREATE INDEX `movientos_bancarios_id_idx` ON `finanzas`.`cheque` (`movimiento_bancario_id` ASC);

CREATE INDEX `chequera_id_idx` ON `finanzas`.`cheque` (`chequera_id` ASC);

CREATE INDEX `condicion_id_idx` ON `finanzas`.`cheque` (`condicion_id` ASC);

CREATE INDEX `fk_cheque_1_idx` ON `finanzas`.`cheque` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`cobrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`cobrador` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`cobrador` (
  `idcobrador` INT(11) NOT NULL AUTO_INCREMENT,
  `cobrador` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idcobrador`),
  CONSTRAINT `fk_cobrador_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_cobrador_usuario_id_idx` ON `finanzas`.`cobrador` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`contacto` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`contacto` (
  `idcontacto` INT(11) NOT NULL AUTO_INCREMENT,
  `contacto` VARCHAR(45) NULL DEFAULT NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `telefono_fijo` VARCHAR(255) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idcontacto`),
  CONSTRAINT `fk_contacto_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_contacto_1_idx` ON `finanzas`.`contacto` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`usuarios_tarjetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`usuarios_tarjetas` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`usuarios_tarjetas` (
  `idusuarios_tarjetas` INT(11) NOT NULL AUTO_INCREMENT,
  `usuarios_tarjeta` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idusuarios_tarjetas`),
  CONSTRAINT `fk_usuarios_tarjetas_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_usuarios_tarjetas_1_idx` ON `finanzas`.`usuarios_tarjetas` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`tarjetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`tarjetas` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`tarjetas` (
  `idtarjetas` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_tarjeta` VARCHAR(45) NOT NULL,
  `dia_del_debito` INT(11) NOT NULL,
  `medio_de_pago_id` INT(11) NOT NULL,
  `limite` DECIMAL(10,0) NULL DEFAULT NULL,
  `cuenta_bancaria_id` INT(11) NOT NULL,
  `movimiento_bancario_id` INT(11) NULL DEFAULT NULL,
  `usuario_tarjeta_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idtarjetas`),
  CONSTRAINT `cta_bancaria_id`
    FOREIGN KEY (`cuenta_bancaria_id`)
    REFERENCES `finanzas`.`cuentas_bancaria` (`idcuentas_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mov_bancario_id`
    FOREIGN KEY (`movimiento_bancario_id`)
    REFERENCES `finanzas`.`movimientos` (`idmovimientos_bancarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarjetas_1`
    FOREIGN KEY (`usuario_tarjeta_id`)
    REFERENCES `finanzas`.`usuarios_tarjetas` (`idusuarios_tarjetas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarjetas_2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `cuenta_bancaria_id_idx` ON `finanzas`.`tarjetas` (`cuenta_bancaria_id` ASC);

CREATE INDEX `movimento_bancario_id_idx` ON `finanzas`.`tarjetas` (`movimiento_bancario_id` ASC);

CREATE INDEX `fk_tarjetas_1_idx` ON `finanzas`.`tarjetas` (`usuario_tarjeta_id` ASC);

CREATE INDEX `fk_tarjetas_2_idx` ON `finanzas`.`tarjetas` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`medio_de_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`medio_de_pago` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`medio_de_pago` (
  `idmedio_de_pago` INT(11) NOT NULL AUTO_INCREMENT,
  `forma_de_pago` VARCHAR(45) NOT NULL,
  `tarjeta_id` INT(11) NULL DEFAULT NULL,
  `cuenta_bancaria_id` INT(11) NULL DEFAULT NULL,
  `cheque_id` INT(11) NULL DEFAULT NULL,
  `caja_id` INT(11) NULL DEFAULT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idmedio_de_pago`),
  CONSTRAINT `chequeid`
    FOREIGN KEY (`cheque_id`)
    REFERENCES `finanzas`.`cheque` (`idcheque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cuenta_bancariaid`
    FOREIGN KEY (`cuenta_bancaria_id`)
    REFERENCES `finanzas`.`cuentas_bancaria` (`idcuentas_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tarjetaid`
    FOREIGN KEY (`tarjeta_id`)
    REFERENCES `finanzas`.`tarjetas` (`idtarjetas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medio_de_pago_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `cheque_id_idx` ON `finanzas`.`medio_de_pago` (`cheque_id` ASC);

CREATE INDEX `cuenta_bancaria_id_idx` ON `finanzas`.`medio_de_pago` (`cuenta_bancaria_id` ASC);

CREATE INDEX `tarjeta_id_idx` ON `finanzas`.`medio_de_pago` (`tarjeta_id` ASC);

CREATE INDEX `fk_medio_de_pago_1_idx` ON `finanzas`.`medio_de_pago` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`clientes` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`clientes` (
  `idclientes` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `honorario` DECIMAL(10,0) NOT NULL,
  `medio_pago_id` INT(11) NOT NULL,
  `cobrador_id` INT(11) NOT NULL,
  `comentario` VARCHAR(255) NULL DEFAULT NULL,
  `cobrado` TINYINT(4) NULL DEFAULT NULL,
  `contacto_id` INT(11) NULL DEFAULT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idclientes`),
  CONSTRAINT `cobrador_id`
    FOREIGN KEY (`cobrador_id`)
    REFERENCES `finanzas`.`cobrador` (`idcobrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contacto_id`
    FOREIGN KEY (`contacto_id`)
    REFERENCES `finanzas`.`contacto` (`idcontacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mediopagoid`
    FOREIGN KEY (`medio_pago_id`)
    REFERENCES `finanzas`.`medio_de_pago` (`idmedio_de_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `cobrador_id_idx` ON `finanzas`.`clientes` (`cobrador_id` ASC);

CREATE INDEX `medio_pago_id_idx` ON `finanzas`.`clientes` (`medio_pago_id` ASC);

CREATE INDEX `contacto_id_idx` ON `finanzas`.`clientes` (`contacto_id` ASC);

CREATE INDEX `fk_clientes_usuario_id_idx` ON `finanzas`.`clientes` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`cuotas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`cuotas` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`cuotas` (
  `idcuotas` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_cuotas` INT(11) NOT NULL,
  PRIMARY KEY (`idcuotas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `finanzas`.`gasto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`gasto` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`gasto` (
  `idgasto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_gasto` VARCHAR(45) NOT NULL,
  `medio_pago_id` INT(11) NULL DEFAULT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idgasto`),
  CONSTRAINT `medio_pago_id`
    FOREIGN KEY (`medio_pago_id`)
    REFERENCES `finanzas`.`medio_de_pago` (`idmedio_de_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gasto_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `medio_pago_id_idx` ON `finanzas`.`gasto` (`medio_pago_id` ASC);

CREATE INDEX `fk_gasto_1_idx` ON `finanzas`.`gasto` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`registro_bancario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`registro_bancario` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`registro_bancario` (
  `idregistro_bancario` INT(11) NOT NULL AUTO_INCREMENT,
  `cuenta_bancaria_id` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `movimiento_id` INT NOT NULL,
  `tipo` TINYINT(4) NULL DEFAULT '0',
  `debe` DECIMAL(10,2) NULL DEFAULT NULL,
  `haber` DECIMAL(10,2) NULL DEFAULT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idregistro_bancario`),
  CONSTRAINT `cuentabancaria_id`
    FOREIGN KEY (`cuenta_bancaria_id`)
    REFERENCES `finanzas`.`cuentas_bancaria` (`idcuentas_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movimientobancario_id`
    FOREIGN KEY (`movimiento_id`)
    REFERENCES `finanzas`.`movimientos` (`idmovimientos_bancarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reg_banco_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `movimiento_bancario_id_idx` ON `finanzas`.`registro_bancario` (`movimiento_id` ASC);

CREATE INDEX `cuenta_bancaria_id_idx` ON `finanzas`.`registro_bancario` (`cuenta_bancaria_id` ASC);

CREATE INDEX `fk_reg_banco_usuario_id_idx` ON `finanzas`.`registro_bancario` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`tipo_gasto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`tipo_gasto` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`tipo_gasto` (
  `idtipo_gasto` INT(11) NOT NULL AUTO_INCREMENT,
  `destino_gasto` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idtipo_gasto`),
  CONSTRAINT `fk_tipo_gasto_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tipo_gasto_1_idx` ON `finanzas`.`tipo_gasto` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`registros_gasto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`registros_gasto` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`registros_gasto` (
  `idregistros_tarjeta` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `nombre_gasto_id` INT(11) NOT NULL,
  `importe` DECIMAL(10,0) NOT NULL,
  `tipo_gasto_id` INT(11) NULL DEFAULT NULL,
  `medio_pago_id` INT(11) NULL DEFAULT NULL,
  `cuotas_id` INT(11) NOT NULL,
  `pagado` TINYINT(4) NOT NULL DEFAULT '1',
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idregistros_tarjeta`),
  CONSTRAINT `cuotasid`
    FOREIGN KEY (`cuotas_id`)
    REFERENCES `finanzas`.`cuotas` (`idcuotas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `medio_pagoid`
    FOREIGN KEY (`medio_pago_id`)
    REFERENCES `finanzas`.`medio_de_pago` (`idmedio_de_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nombre_gastoid`
    FOREIGN KEY (`nombre_gasto_id`)
    REFERENCES `finanzas`.`gasto` (`idgasto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo_gastoid`
    FOREIGN KEY (`tipo_gasto_id`)
    REFERENCES `finanzas`.`tipo_gasto` (`idtipo_gasto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reg_gasto_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `nombre_gasto_id_idx` ON `finanzas`.`registros_gasto` (`nombre_gasto_id` ASC);

CREATE INDEX `tipo_gasto_id_idx` ON `finanzas`.`registros_gasto` (`tipo_gasto_id` ASC);

CREATE INDEX `medio_pago_id_idx` ON `finanzas`.`registros_gasto` (`medio_pago_id` ASC);

CREATE INDEX `cuotas_id_idx` ON `finanzas`.`registros_gasto` (`cuotas_id` ASC);

CREATE INDEX `fk_reg_gasto_usuario_id_idx` ON `finanzas`.`registros_gasto` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `finanzas`.`caja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finanzas`.`caja` ;

CREATE TABLE IF NOT EXISTS `finanzas`.`caja` (
  `idcaja` INT UNSIGNED NOT NULL,
  `caja` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  `debe` DECIMAL(10,2) NULL,
  `haber` DECIMAL(10,2) NULL,
  `saldo` DECIMAL(10,2) NULL,
  `movimiento_id` INT NOT NULL,
  PRIMARY KEY (`idcaja`),
  CONSTRAINT `fk_caja_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `finanzas`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caja_2`
    FOREIGN KEY (`movimiento_id`)
    REFERENCES `finanzas`.`movimientos` (`idmovimientos_bancarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `caja_UNIQUE` ON `finanzas`.`caja` (`caja` ASC);

CREATE INDEX `fk_caja_1_idx` ON `finanzas`.`caja` (`usuario_id` ASC);

CREATE INDEX `fk_caja_2_idx` ON `finanzas`.`caja` (`movimiento_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
