-- MySQL Script generated by MySQL Workbench
-- Sun Sep 24 20:49:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`bancos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bancos` (
  `idbancos` INT NOT NULL AUTO_INCREMENT,
  `banco_nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`idbancos`))
ENGINE = InnoDB
COMMENT = '					';

CREATE UNIQUE INDEX `idBANCOS_UNIQUE` ON `mydb`.`bancos` (`idbancos` ASC);

CREATE UNIQUE INDEX `banco_nombre_UNIQUE` ON `mydb`.`bancos` (`banco_nombre` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`cuentas_bancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuentas_bancaria` (
  `idcuentas_bancaria` INT NOT NULL AUTO_INCREMENT,
  `num_cuenta` VARCHAR(45) NOT NULL,
  `banco_id` INT NOT NULL,
  PRIMARY KEY (`idcuentas_bancaria`),
  CONSTRAINT `banco_id`
    FOREIGN KEY (`banco_id`)
    REFERENCES `mydb`.`bancos` (`idbancos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_cuentas_bancaria_UNIQUE` ON `mydb`.`cuentas_bancaria` (`idcuentas_bancaria` ASC);

CREATE UNIQUE INDEX `num_cuenta_UNIQUE` ON `mydb`.`cuentas_bancaria` (`num_cuenta` ASC);

CREATE INDEX `banco_id_idx` ON `mydb`.`cuentas_bancaria` (`banco_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`movimientos_bancarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movimientos_bancarios` (
  `idmovimientos_bancarios` INT NOT NULL AUTO_INCREMENT,
  `movimientos_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmovimientos_bancarios`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idmovimientos_bancarios_UNIQUE` ON `mydb`.`movimientos_bancarios` (`idmovimientos_bancarios` ASC);

CREATE UNIQUE INDEX `movimientos_nombre_UNIQUE` ON `mydb`.`movimientos_bancarios` (`movimientos_nombre` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`chequera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chequera` (
  `idchequera` INT NOT NULL AUTO_INCREMENT,
  `numero_chequera` INT NOT NULL,
  `cantidad_cheques` INT NOT NULL,
  `desde` INT NOT NULL,
  `hasta` INT NOT NULL,
  `cuenta_bancaria_id` INT NOT NULL,
  PRIMARY KEY (`idchequera`),
  CONSTRAINT `cuenta_bancaria_id`
    FOREIGN KEY (`cuenta_bancaria_id`)
    REFERENCES `mydb`.`cuentas_bancaria` (`idcuentas_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `cuenta_bancaria_id_idx` ON `mydb`.`chequera` (`cuenta_bancaria_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`condicion_cheque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`condicion_cheque` (
  `idcondicion_cheque` INT NOT NULL AUTO_INCREMENT,
  `condicion_cheque` VARCHAR(45) NULL,
  PRIMARY KEY (`idcondicion_cheque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cheque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cheque` (
  `idcheque` INT NOT NULL AUTO_INCREMENT,
  `numero_cheque` INT NOT NULL,
  `importe_cheque` DECIMAL NOT NULL,
  `fecha_emision` DATE NOT NULL,
  `fecha_cobro` DATE NOT NULL,
  `destinatario` VARCHAR(45) NOT NULL,
  `estado_cheque` VARCHAR(45) NULL,
  `movimiento_bancario_id` INT NOT NULL,
  `chequera_id` INT NULL,
  `condicion_id` INT NULL,
  PRIMARY KEY (`idcheque`),
  CONSTRAINT `moviento_bancario_id`
    FOREIGN KEY (`movimiento_bancario_id`)
    REFERENCES `mydb`.`movimientos_bancarios` (`idmovimientos_bancarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chequera_id`
    FOREIGN KEY (`chequera_id`)
    REFERENCES `mydb`.`chequera` (`idchequera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `condicion_id`
    FOREIGN KEY (`condicion_id`)
    REFERENCES `mydb`.`condicion_cheque` (`idcondicion_cheque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcheque_UNIQUE` ON `mydb`.`cheque` (`idcheque` ASC);

CREATE UNIQUE INDEX `numero_cheque_UNIQUE` ON `mydb`.`cheque` (`numero_cheque` ASC);

CREATE INDEX `movientos_bancarios_id_idx` ON `mydb`.`cheque` (`movimiento_bancario_id` ASC);

CREATE INDEX `chequera_id_idx` ON `mydb`.`cheque` (`chequera_id` ASC);

CREATE INDEX `condicion_id_idx` ON `mydb`.`cheque` (`condicion_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`registro_bancario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registro_bancario` (
  `idregistro_bancario` INT NOT NULL AUTO_INCREMENT,
  `cuenta_bancaria_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `movimiento_bancario_id` INT NOT NULL,
  `tipo` TINYINT NULL DEFAULT 0,
  `debe` DECIMAL NULL,
  `haber` DECIMAL NULL,
  PRIMARY KEY (`idregistro_bancario`),
  CONSTRAINT `cuentabancaria_id`
    FOREIGN KEY (`cuenta_bancaria_id`)
    REFERENCES `mydb`.`cuentas_bancaria` (`idcuentas_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movimientobancario_id`
    FOREIGN KEY (`movimiento_bancario_id`)
    REFERENCES `mydb`.`movimientos_bancarios` (`idmovimientos_bancarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `movimiento_bancario_id_idx` ON `mydb`.`registro_bancario` (`movimiento_bancario_id` ASC);

CREATE INDEX `cuenta_bancaria_id_idx` ON `mydb`.`registro_bancario` (`cuenta_bancaria_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`usuarios_tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios_tarjetas` (
  `idusuarios_tarjetas` INT NOT NULL AUTO_INCREMENT,
  `usuarios_tarjeta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuarios_tarjetas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tarjetas` (
  `idtarjetas` INT NOT NULL AUTO_INCREMENT,
  `nombre_tarjeta` VARCHAR(45) NOT NULL,
  `dia_del_debito` INT NOT NULL,
  `medio_de_pago_id` INT NOT NULL,
  `limite` DECIMAL NULL,
  `cuenta_bancaria_id` INT NOT NULL,
  `movimiento_bancario_id` INT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idtarjetas`),
  CONSTRAINT `cta_bancaria_id`
    FOREIGN KEY (`cuenta_bancaria_id`)
    REFERENCES `mydb`.`cuentas_bancaria` (`idcuentas_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mov_bancario_id`
    FOREIGN KEY (`movimiento_bancario_id`)
    REFERENCES `mydb`.`movimientos_bancarios` (`idmovimientos_bancarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usu_tarjeta_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuarios_tarjetas` (`idusuarios_tarjetas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `cuenta_bancaria_id_idx` ON `mydb`.`tarjetas` (`cuenta_bancaria_id` ASC);

CREATE INDEX `movimento_bancario_id_idx` ON `mydb`.`tarjetas` (`movimiento_bancario_id` ASC);

CREATE INDEX `usuario_tarjeta_id_idx` ON `mydb`.`tarjetas` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`medio_de_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medio_de_pago` (
  `idmedio_de_pago` INT NOT NULL AUTO_INCREMENT,
  `forma_de_pago` VARCHAR(45) NOT NULL,
  `tarjeta_id` INT NULL,
  `cuenta_bancaria_id` INT NULL,
  `cheque_id` INT NULL,
  `caja_id` INT NULL,
  PRIMARY KEY (`idmedio_de_pago`),
  CONSTRAINT `chequeid`
    FOREIGN KEY (`cheque_id`)
    REFERENCES `mydb`.`cheque` (`idcheque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cuenta_bancariaid`
    FOREIGN KEY (`cuenta_bancaria_id`)
    REFERENCES `mydb`.`cuentas_bancaria` (`idcuentas_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tarjetaid`
    FOREIGN KEY (`tarjeta_id`)
    REFERENCES `mydb`.`tarjetas` (`idtarjetas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `cheque_id_idx` ON `mydb`.`medio_de_pago` (`cheque_id` ASC);

CREATE INDEX `cuenta_bancaria_id_idx` ON `mydb`.`medio_de_pago` (`cuenta_bancaria_id` ASC);

CREATE INDEX `tarjeta_id_idx` ON `mydb`.`medio_de_pago` (`tarjeta_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gasto` (
  `idgasto` INT NOT NULL AUTO_INCREMENT,
  `nombre_gasto` VARCHAR(45) NOT NULL,
  `medio_pago_id` INT NULL,
  PRIMARY KEY (`idgasto`),
  CONSTRAINT `medio_pago_id`
    FOREIGN KEY (`medio_pago_id`)
    REFERENCES `mydb`.`medio_de_pago` (`idmedio_de_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `medio_pago_id_idx` ON `mydb`.`gasto` (`medio_pago_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`tipo_gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_gasto` (
  `idtipo_gasto` INT NOT NULL AUTO_INCREMENT,
  `destino_gasto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_gasto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuotas` (
  `idcuotas` INT NOT NULL AUTO_INCREMENT,
  `numero_cuotas` INT NOT NULL,
  PRIMARY KEY (`idcuotas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registros_gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registros_gasto` (
  `idregistros_tarjeta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `nombre_gasto_id` INT NOT NULL,
  `importe` DECIMAL NOT NULL,
  `tipo_gasto_id` INT NULL,
  `medio_pago_id` INT NULL,
  `cuotas_id` INT NOT NULL,
  `pagado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idregistros_tarjeta`),
  CONSTRAINT `nombre_gastoid`
    FOREIGN KEY (`nombre_gasto_id`)
    REFERENCES `mydb`.`gasto` (`idgasto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo_gastoid`
    FOREIGN KEY (`tipo_gasto_id`)
    REFERENCES `mydb`.`tipo_gasto` (`idtipo_gasto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `medio_pagoid`
    FOREIGN KEY (`medio_pago_id`)
    REFERENCES `mydb`.`medio_de_pago` (`idmedio_de_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cuotasid`
    FOREIGN KEY (`cuotas_id`)
    REFERENCES `mydb`.`cuotas` (`idcuotas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `nombre_gasto_id_idx` ON `mydb`.`registros_gasto` (`nombre_gasto_id` ASC);

CREATE INDEX `tipo_gasto_id_idx` ON `mydb`.`registros_gasto` (`tipo_gasto_id` ASC);

CREATE INDEX `medio_pago_id_idx` ON `mydb`.`registros_gasto` (`medio_pago_id` ASC);

CREATE INDEX `cuotas_id_idx` ON `mydb`.`registros_gasto` (`cuotas_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`cobrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cobrador` (
  `idcobrador` INT NOT NULL AUTO_INCREMENT,
  `cobrador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcobrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contacto` (
  `idcontacto` INT NOT NULL AUTO_INCREMENT,
  `contacto` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `direccion` VARCHAR(255) NULL,
  `telefono_fijo` VARCHAR(255) NULL,
  `celular` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `honorario` DECIMAL NOT NULL,
  `medio_pago_id` INT NOT NULL,
  `cobrador_id` INT NOT NULL,
  `comentario` VARCHAR(255) NULL,
  `cobrado` TINYINT NULL,
  `contacto_id` INT NULL,
  PRIMARY KEY (`idclientes`),
  CONSTRAINT `cobrador_id`
    FOREIGN KEY (`cobrador_id`)
    REFERENCES `mydb`.`cobrador` (`idcobrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mediopagoid`
    FOREIGN KEY (`medio_pago_id`)
    REFERENCES `mydb`.`medio_de_pago` (`idmedio_de_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contacto_id`
    FOREIGN KEY (`contacto_id`)
    REFERENCES `mydb`.`contacto` (`idcontacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `cobrador_id_idx` ON `mydb`.`clientes` (`cobrador_id` ASC);

CREATE INDEX `medio_pago_id_idx` ON `mydb`.`clientes` (`medio_pago_id` ASC);

CREATE INDEX `contacto_id_idx` ON `mydb`.`clientes` (`contacto_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
